#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Andrewmaster\Sandbox\Application\Console\ConsoleKernel;

$application = new Application('Sandbox Console', '1.0.0');
ConsoleKernel::boot($application);

try {
    $exitCode = $application->run();
    exit($exitCode);
} catch (Throwable $e) {
    fwrite(STDERR, $e->getMessage() . PHP_EOL);
    exit(1);
}
